language: python
python:
  - 3.6
env:
  - CODECOV_TOKEN="e042fc33-35cf-4e14-b8f5-8285703bdbeb"
install:
  - pip install codecov
  - pip install pylint
  - pip install pygame
  - pip install pyanim
script:
  - ./tests.py
after_success:
  - pylint Main.py