language: python
python:
  - 3.6
env:
  - CODECOV_TOKEN="0b623512-8f4e-4485-9d55-3bc3093fb2a0"
install:
  - pip install codecov
  - pip install pylint
  - pip install pygame==1.9.3
  - pip install pyganim
script:
  - bash <(curl -s https://codecov.io/bash)
after_success:
  - pylint Game/GameLoop.py